# This is only for use with the pre-commit.ci service so that pull requests
# are automatically formatted and ./dist/ is updated
#
# Do not add any other pre-commit hooks here, everything should be done in
# package.json so that Python is not required.

repos:
  - repo: https://github.com/manics/precommit-npm-run-scripts
    rev: 3df79dd8671bc76fb4598930f5f4b4e7d05e5a56
    hooks:
      - id: npm-run-scripts
        args: [format, package]
